### ISSUE TITLE
Sessions on Home page should be searchable on all content available in Session table

### ISSUE THREAD

**Issue by mavericksid** [knoldus/knolx-portal#111]
Knolx sessions available on home page should be searchable on all content available in Sessions table, currently only "Search by Email" is available.

**Comment by mavericksid** [comment]
@Aakash06 
I guess the changes for searchable sessions looks good. Please remove the the gap between navbar and search box then we can mark this issue as done.

**Comment by Aakash06** [comment]
Yes I have removed the gap between navbar and search box
